# LYCA EDA, Close ports after sending!

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objs as go

Load Data

In [2]:
import os

def get_files_in_directory(directory):
    # Initialize an empty list to store file names
    files = []

    # Loop through all files and directories in the specified directory
    for file_name in os.listdir(directory):
        # Check if the current entry is a file
        if os.path.isfile(os.path.join(directory, file_name)):
            # If it's a file, add its name to the list
            files.append(file_name)

    return files

# Example usage
directory = "data/lyca_nl/"
files_in_directory = get_files_in_directory(directory)
print("Files in directory:", files_in_directory)

Files in directory: ['data_Lyca_server_7.csv', 'data_Lyca_server_8.csv', 'data_lyca_7_rapid_phone.csv', 'data_lyca_3_phone_long.csv', 'data_Lyca_1_phone.csv', 'data_Lyca_server_9.csv', 'data_Lyca_server_3.csv', 'data_lyca_6_phone_rapid.csv', 'data_Lyca_server_10.csv', 'Lyca_LONG_phone_10.csv', 'data_Lyca_5_phone_long.csv', 'data_Lyca_server_2.csv', 'data_Lyca_server_6.csv', 'data_Lyca_server_5.csv', 'data_lyca_4_long_phone.csv', 'data_Lyca_2_phone.csv', 'Lyca_LONG_phone_8.csv', 'data_Lyca_server_1.csv', 'data_Lyca_server_4.csv', 'Lyca_LONG_phone_9.csv']

Open File 1 and visualize it

In [ ]:
# Load data and clean up

df_phone = pd.read_csv("data/lyca_nl/data_Lyca_1_phone.csv")
df_server = pd.read_csv("data/lyca_nl/data_Lyca_server_1.csv")
trimmed_columns = {col: col.strip() for col in df_server.columns}
df_server = df_server.rename(columns=trimmed_columns)
trimmed_columns = {col: col.strip() for col in df_phone.columns}
df_phone = df_phone.rename(columns=trimmed_columns)
df_merged = df_phone.merge(df_server, how="inner", on="Message id")
df_merged.sort_values(by="Time_y")
df_merged["Time_y"] = df_merged["Time_y"].astype(int)
df_merged["time_difference_y"] = df_merged['Time_y'].diff()
df_merged.sort_values(by="Time_x")
df_merged["Time_x"] = df_merged["Time_x"].astype(int)
df_merged["time_difference_x"] = df_merged['Time_x'].diff()
df_merged["Sender Port_x"] = df_merged["Sender Port_x"].astype(str)
df_merged["Sender Port_y"] = df_merged["Sender Port_y"].astype(str)


print(f"Number of rows {len(df_merged.index)}")
# Visualize 

# Create a line chart using Plotly
fig = go.Figure()

# Add a line trace
fig.add_trace(go.Scatter(x=df_merged['Time_x'], y=df_merged['Sender Port_y'], mode='lines', name='Port_y'))

# Update layout
fig.update_layout(title='Line Chart of Time and Value for set 1',
                  xaxis_title='Time',
                  yaxis_title='Value')

# Show the plot
fig.show()

Open file 2 and visualize

In [ ]:
# Load data and clean up

df_phone = pd.read_csv("data/lyca_nl/data_Lyca_2_phone.csv")
df_server = pd.read_csv("data/lyca_nl/data_Lyca_server_2.csv")
trimmed_columns = {col: col.strip() for col in df_server.columns}
df_server = df_server.rename(columns=trimmed_columns)
trimmed_columns = {col: col.strip() for col in df_phone.columns}
df_phone = df_phone.rename(columns=trimmed_columns)
df_merged = df_phone.merge(df_server, how="inner", on="Message id")
df_merged.sort_values(by="Time_y")
df_merged["Time_y"] = df_merged["Time_y"].astype(int)
df_merged["time_difference_y"] = df_merged['Time_y'].diff()
df_merged.sort_values(by="Time_x")
df_merged["Time_x"] = df_merged["Time_x"].astype(int)
df_merged["time_difference_x"] = df_merged['Time_x'].diff()
df_merged["Sender Port_x"] = df_merged["Sender Port_x"].astype(str)
df_merged["Sender Port_y"] = df_merged["Sender Port_y"].astype(str)

print(f"Number of rows {len(df_merged.index)}")


# Visualize 

# Create a line chart using Plotly
fig = go.Figure()

# Add a line trace
fig.add_trace(go.Scatter(x=df_merged['Time_x'], y=df_merged['Sender Port_y'], mode='lines', name='Port_y'))

# Update layout
fig.update_layout(title='Line Chart of Time and Value for set 2',
                  xaxis_title='Time',
                  yaxis_title='Value')

# Show the plot
fig.show()

Open file 3 and visualize

In [ ]:
# Load data and clean up

df_phone = pd.read_csv("data/lyca_nl/data_lyca_3_phone_long.csv")
df_server = pd.read_csv("data/lyca_nl/data_Lyca_server_3.csv")
trimmed_columns = {col: col.strip() for col in df_server.columns}
df_server = df_server.rename(columns=trimmed_columns)
trimmed_columns = {col: col.strip() for col in df_phone.columns}
df_phone = df_phone.rename(columns=trimmed_columns)
df_merged = df_phone.merge(df_server, how="inner", on="Message id")
df_merged.sort_values(by="Time_y")
df_merged["Time_y"] = df_merged["Time_y"].astype(int)
df_merged["time_difference_y"] = df_merged['Time_y'].diff()
df_merged.sort_values(by="Time_x")
df_merged["Time_x"] = df_merged["Time_x"].astype(int)
df_merged["time_difference_x"] = df_merged['Time_x'].diff()
df_merged["Sender Port_x"] = df_merged["Sender Port_x"].astype(str)
df_merged["Sender Port_y"] = df_merged["Sender Port_y"].astype(str)

print(f"Number of rows {len(df_merged.index)}")

# Visualize 

# Create a line chart using Plotly
fig = go.Figure()

# Add a line trace
fig.add_trace(go.Scatter(x=df_merged['Time_x'], y=df_merged['Sender Port_y'], mode='lines', name='Port_y'))

# Update layout
fig.update_layout(title='Line Chart of Time and Value for set 2',
                  xaxis_title='Time',
                  yaxis_title='Value')

# Show the plot
fig.show()

Concatenate all of them

In [3]:
df = pd.DataFrame()
for i in range(1,11):
    names = list(filter(lambda x: f"_{i}" in x, files_in_directory))
    phone = list(filter(lambda x: "phone" in x, names))[0]
    server = list(filter(lambda x: "server" in x, names))[0]
    df_phone = pd.read_csv(f"data/lyca_nl/{phone}")
    df_server = pd.read_csv(f"data/lyca_nl/{server}")
    trimmed_columns = {col: col.strip() for col in df_server.columns}
    df_server = df_server.rename(columns=trimmed_columns)
    trimmed_columns = {col: col.strip() for col in df_phone.columns}
    df_phone = df_phone.rename(columns=trimmed_columns)
    df_merged = df_phone.merge(df_server, how="inner", on="Message id")
    df_merged.sort_values(by="Time_y")
    df_merged["Time_y"] = df_merged["Time_y"].astype(int)
    df_merged["time_difference_y"] = df_merged['Time_y'].diff()
    df_merged.sort_values(by="Time_x")
    df_merged["Time_x"] = df_merged["Time_x"].astype(int)
    df_merged["time_difference_x"] = df_merged['Time_x'].diff()
    df_merged["Sender Port_x"] = df_merged["Sender Port_x"].astype(int)
    df_merged["Sender Port_y"] = df_merged["Sender Port_y"].astype(int)
    df_merged["label"] = i
    df_merged = df_merged[["Time_x", 'Sender Port_x', 'Sender Port_y', "label"]]
    df = pd.concat([df, df_merged], ignore_index=True)

df

               Time_x  Sender Port_x  Sender Port_y  label
0       1708107803585           1831          63833      2
1       1708107803607          36192          53922      2
2       1708107803629          16452          15691      2
3       1708107803651          33864          46725      2
4       1708107803674          40637          36204      2
...               ...            ...            ...    ...
288376  1708444339049          58060          26295      9
288377  1708444339434          29135          47414      9
288378  1708444339818          38907          31873      9
288379  1708444340203          57776          21762      9
288380  1708444340589          45967          14901      9

[288381 rows x 4 columns]

In [ ]:
import matplotlib as plt
df["time"] = pd.to_datetime(df["Time_x"], unit='ms' )
# # Add a line trace
# fig.add_trace(go.Scatter(x=df['time'], y=df['Sender Port_y'], name=df["label"], mode='lines' ))
df["label"] = df["label"].astype(str)
# Get unique categories
categories = df['label'].unique()

colors = ['blue', 'red', 'green', 'cyan', 'magenta', 'yellow', 'black', 'white', 'gray', 'purple']


# Create a dictionary to map categories to colors
color_mapping = {category: color for category, color in zip(categories, colors)}


# Create a scatter plot using Plotly
fig = go.Figure()

# Add a scatter trace with colored markers for each category
for category, color in color_mapping.items():
    subset = df[df['label'] == category]
    fig.add_trace(go.Scatter(x=subset['time'], y=subset['Sender Port_y'], mode='lines+markers', 
                                                          line=dict(color=color), name=category))

# Update layout
fig.update_layout(title='Line Chart of Time and Value',
                  xaxis_title='Time',
                  yaxis_title='Value')

# Show the plot
fig.show()

In [6]:
l = [[0]]
THRESHOLD = 1
prev = df.iloc[0]
for index, row in df.iterrows():
    

    if abs(row["Sender Port_y"] - prev["Sender Port_y"]) > THRESHOLD or row["Time_x"] - prev["Time_x"] > 10000:
        l[-1].append(index -1)
        l.append([index])


    prev = row
len(l)
# print(l)
# print(len(l))
# l.pop()
# differences = [ e-b  for b,e in l ]
# print(differences)
# print(len(differences))

# filtered = list(filter(lambda x: x < 5, differences))
# len(filtered)




# differences_df = pd.DataFrame(differences, columns=["diffs"])
# fig = go.Figure(data=[go.Histogram(x=differences_df["diffs"], nbinsx=len(differences))])
# fig.update_layout(title='Histogram of Sample Data', xaxis_title='Value', yaxis_title='Frequency')
# fig.show()
# # Calculate the PDF using numpy
# data = differences
# density, bins = np.histogram(data, bins=10, density=True)
# midpoints = (bins[1:] + bins[:-1]) / 2

# # Create line plot of the PDF using Plotly
# fig = go.Figure(data=[go.Scatter(x=midpoints, y=density, mode='lines')])
# fig.update_layout(title='Probability Density Function of Sample Data', xaxis_title='Value', yaxis_title='Density')
# fig.show()

288299

In [9]:
df.iloc[100000:100050]

               Time_x  Sender Port_x  Sender Port_y  label
100000  1708175187587          47830          19977      4
100001  1708175187992          15175          17912      4
100002  1708175188397          55128           8234      4
100003  1708175188803          26123          57560      4
100004  1708175189209          17381          48539      4
100005  1708175189615           1235          20623      4
100006  1708175190021          30190           9477      4
100007  1708175190427           8576          32404      4
100008  1708175190833          16607           5516      4
100009  1708175191239          48208          29271      4
100010  1708175191644          56546          57811      4
100011  1708175192050          15298          19985      4
100012  1708175192456          18588          48248      4
100013  1708175192863           4340          13812      4
100014  1708175193268          40651          30926      4
100015  1708175193673           6476          28704      4
100016  1708175194078          48546          60022      4
100017  1708175194484          18681          55342      4
100018  1708175194889          36230          50385      4
100019  1708175195296          52574          38375      4
100020  1708175195702          49819           9485      4
100021  1708175196109          41455          23104      4
100022  1708175196514           7981          44203      4
100023  1708175196920          21289          47044      4
100024  1708175197326          26413          28677      4
100025  1708175197733           2238          25325      4
100026  1708175198139          32724          16300      4
100027  1708175198544          33242          33991      4
100028  1708175198949          13222          50375      4
100029  1708175199356          48396          25341      4
100030  1708175199761          47467          18152      4
100031  1708175200166          20120          10451      4
100032  1708175200572          46485          42344      4
100033  1708175200977          57163          60026      4
100034  1708175201383          27317          61548      4
100035  1708175201789          22060           8584      4
100036  1708175202195          62637          19967      4
100037  1708175202600           6977          19976      4
100038  1708175203007          35895          17248      4
100039  1708175203413          19930          11661      4
100040  1708175203820          62998          20369      4
100041  1708175204226          62059           4861      4
100042  1708175204632          41793          40446      4
100043  1708175205037          30460          37744      4
100044  1708175205443          20946          18778      4
100045  1708175205848          19949          28086      4
100046  1708175206254           5570          37108      4
100047  1708175206661          50346          14788      4
100048  1708175207066           1043          31542      4
100049  1708175207471          29463          53250      4

# LYCA, WHEN CLOSING THE PORTS SEEMS TO BE COMPLETELY RANDOM!!!!

Wikipedia says they use KPN but it does not behave like KPN

In [23]:
grouped = df.groupby(["Sender Port_x", "Sender Port_y"],as_index=False).size()
len(grouped[grouped['size'] >1])

17

In [17]:
df['Sender Port_y'].unique()

50442

### Seems that there is no repeating pair  X -> Y probably just an unsorted FIFO queue.

### JUST 17 repetitions in 280k rows. Probably just a huge unsorted queue that everyone consumes ports from!!!